"""init

Revision ID: 5a8074e6aa9f
Revises: 
Create Date: 2020-12-31 14:56:20.127024

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5a8074e6aa9f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chargepoint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=20), nullable=False),
    sa.Column('vendor', sa.String(length=20), nullable=False),
    sa.Column('serial_number', sa.String(length=25), nullable=True),
    sa.Column('firmware', sa.String(length=50), nullable=True),
    sa.Column('type', sa.String(length=25), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('boot_timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.Column('identity', sa.String(length=50), nullable=False),
    sa.Column('connected', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity')
    )
    op.create_index(op.f('ix_chargepoint_id'), 'chargepoint', ['id'], unique=False)
    op.create_table('tokengroup',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_tokengroup_id'), 'tokengroup', ['id'], unique=False)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('first_name', sa.String(length=150), nullable=False),
    sa.Column('last_name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('is_staff', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('date_joined', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_table('vehiclemanufacturer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemanufacturer_id'), 'vehiclemanufacturer', ['id'], unique=False)
    op.create_table('connector',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('chargepoint_id', sa.Integer(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.Column('in_use', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['chargepoint_id'], ['chargepoint.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connector_id', 'chargepoint_id')
    )
    op.create_index(op.f('ix_connector_chargepoint_id'), 'connector', ['chargepoint_id'], unique=False)
    op.create_index(op.f('ix_connector_id'), 'connector', ['id'], unique=False)
    op.create_table('token',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=20), nullable=False),
    sa.Column('token_group_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['token_group_id'], ['tokengroup.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    op.create_index(op.f('ix_token_id'), 'token', ['id'], unique=False)
    op.create_index(op.f('ix_token_token_group_id'), 'token', ['token_group_id'], unique=False)
    op.create_index(op.f('ix_token_user_id'), 'token', ['user_id'], unique=False)
    op.create_table('vehiclemodel',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manufacturer_id', sa.Integer(), nullable=True),
    sa.Column('model', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['manufacturer_id'], ['vehiclemanufacturer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehiclemodel_id'), 'vehiclemodel', ['id'], unique=False)
    op.create_index(op.f('ix_vehiclemodel_manufacturer_id'), 'vehiclemodel', ['manufacturer_id'], unique=False)
    op.create_table('authorizationrequest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_id', sa.Integer(), nullable=True),
    sa.Column('chargepoint_id', sa.Integer(), nullable=False),
    sa.Column('token_string', sa.String(length=20), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chargepoint_id'], ['chargepoint.id'], ),
    sa.ForeignKeyConstraint(['token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authorizationrequest_chargepoint_id'), 'authorizationrequest', ['chargepoint_id'], unique=False)
    op.create_index(op.f('ix_authorizationrequest_id'), 'authorizationrequest', ['id'], unique=False)
    op.create_index(op.f('ix_authorizationrequest_token_id'), 'authorizationrequest', ['token_id'], unique=False)
    op.create_table('chargepointerror',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('info', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('vendor_id', sa.String(length=255), nullable=True),
    sa.Column('vendor_error_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chargepointerror_connector_id'), 'chargepointerror', ['connector_id'], unique=False)
    op.create_index(op.f('ix_chargepointerror_id'), 'chargepointerror', ['id'], unique=False)
    op.create_table('inprogresstransaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meter_start', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('connector_id', sa.Integer(), nullable=False),
    sa.Column('start_token_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.ForeignKeyConstraint(['start_token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inprogresstransaction_connector_id'), 'inprogresstransaction', ['connector_id'], unique=False)
    op.create_index(op.f('ix_inprogresstransaction_id'), 'inprogresstransaction', ['id'], unique=False)
    op.create_index(op.f('ix_inprogresstransaction_start_token_id'), 'inprogresstransaction', ['start_token_id'], unique=False)
    op.create_table('transaction',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('start_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('duration', postgresql.INTERVAL(), nullable=False),
    sa.Column('meter_start', sa.Integer(), nullable=False),
    sa.Column('meter_stop', sa.Integer(), nullable=False),
    sa.Column('meter_used', sa.Integer(), nullable=False),
    sa.Column('stop_reason', sa.Text(), nullable=True),
    sa.Column('connector_id', sa.Integer(), nullable=True),
    sa.Column('end_token_id', sa.Integer(), nullable=True),
    sa.Column('start_token_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['connector_id'], ['connector.id'], ),
    sa.ForeignKeyConstraint(['end_token_id'], ['token.id'], ),
    sa.ForeignKeyConstraint(['start_token_id'], ['token.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transaction_connector_id'), 'transaction', ['connector_id'], unique=False)
    op.create_index(op.f('ix_transaction_end_token_id'), 'transaction', ['end_token_id'], unique=False)
    op.create_index(op.f('ix_transaction_id'), 'transaction', ['id'], unique=False)
    op.create_index(op.f('ix_transaction_start_token_id'), 'transaction', ['start_token_id'], unique=False)
    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=True),
    sa.Column('registration', sa.String(length=20), nullable=False),
    sa.Column('owner', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['vehiclemodel.id'], ),
    sa.ForeignKeyConstraint(['owner'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vehicle_id'), 'vehicle', ['id'], unique=False)
    op.create_index(op.f('ix_vehicle_model_id'), 'vehicle', ['model_id'], unique=False)
    op.create_table('vehicle_users',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_users')
    op.drop_index(op.f('ix_vehicle_model_id'), table_name='vehicle')
    op.drop_index(op.f('ix_vehicle_id'), table_name='vehicle')
    op.drop_table('vehicle')
    op.drop_index(op.f('ix_transaction_start_token_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_end_token_id'), table_name='transaction')
    op.drop_index(op.f('ix_transaction_connector_id'), table_name='transaction')
    op.drop_table('transaction')
    op.drop_index(op.f('ix_inprogresstransaction_start_token_id'), table_name='inprogresstransaction')
    op.drop_index(op.f('ix_inprogresstransaction_id'), table_name='inprogresstransaction')
    op.drop_index(op.f('ix_inprogresstransaction_connector_id'), table_name='inprogresstransaction')
    op.drop_table('inprogresstransaction')
    op.drop_index(op.f('ix_chargepointerror_id'), table_name='chargepointerror')
    op.drop_index(op.f('ix_chargepointerror_connector_id'), table_name='chargepointerror')
    op.drop_table('chargepointerror')
    op.drop_index(op.f('ix_authorizationrequest_token_id'), table_name='authorizationrequest')
    op.drop_index(op.f('ix_authorizationrequest_id'), table_name='authorizationrequest')
    op.drop_index(op.f('ix_authorizationrequest_chargepoint_id'), table_name='authorizationrequest')
    op.drop_table('authorizationrequest')
    op.drop_index(op.f('ix_vehiclemodel_manufacturer_id'), table_name='vehiclemodel')
    op.drop_index(op.f('ix_vehiclemodel_id'), table_name='vehiclemodel')
    op.drop_table('vehiclemodel')
    op.drop_index(op.f('ix_token_user_id'), table_name='token')
    op.drop_index(op.f('ix_token_token_group_id'), table_name='token')
    op.drop_index(op.f('ix_token_id'), table_name='token')
    op.drop_table('token')
    op.drop_index(op.f('ix_connector_id'), table_name='connector')
    op.drop_index(op.f('ix_connector_chargepoint_id'), table_name='connector')
    op.drop_table('connector')
    op.drop_index(op.f('ix_vehiclemanufacturer_id'), table_name='vehiclemanufacturer')
    op.drop_table('vehiclemanufacturer')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_tokengroup_id'), table_name='tokengroup')
    op.drop_table('tokengroup')
    op.drop_index(op.f('ix_chargepoint_id'), table_name='chargepoint')
    op.drop_table('chargepoint')
    # ### end Alembic commands ###
