"""Add billing tables

Revision ID: 8aa1e29174b1
Revises: d216ee3d9b21
Create Date: 2021-03-10 22:11:25.096760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8aa1e29174b1'
down_revision = 'd216ee3d9b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_id'), 'account', ['id'], unique=False)
    op.create_index(op.f('ix_account_user_id'), 'account', ['user_id'], unique=False)
    op.create_table('accountstatement',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('closing_balance', sa.Float(), nullable=False),
    sa.Column('total_credit', sa.Float(), nullable=False),
    sa.Column('total_debit', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accountstatement_account_id'), 'accountstatement', ['account_id'], unique=False)
    op.create_index(op.f('ix_accountstatement_id'), 'accountstatement', ['id'], unique=False)
    op.create_table('credit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_credit_account_id'), 'credit', ['account_id'], unique=False)
    op.create_index(op.f('ix_credit_id'), 'credit', ['id'], unique=False)
    op.create_table('debit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debit_account_id'), 'debit', ['account_id'], unique=False)
    op.create_index(op.f('ix_debit_id'), 'debit', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_debit_id'), table_name='debit')
    op.drop_index(op.f('ix_debit_account_id'), table_name='debit')
    op.drop_table('debit')
    op.drop_index(op.f('ix_credit_id'), table_name='credit')
    op.drop_index(op.f('ix_credit_account_id'), table_name='credit')
    op.drop_table('credit')
    op.drop_index(op.f('ix_accountstatement_id'), table_name='accountstatement')
    op.drop_index(op.f('ix_accountstatement_account_id'), table_name='accountstatement')
    op.drop_table('accountstatement')
    op.drop_index(op.f('ix_account_user_id'), table_name='account')
    op.drop_index(op.f('ix_account_id'), table_name='account')
    op.drop_table('account')
    # ### end Alembic commands ###
